[17기 박재현] Refactor: ProductCartView
wecode-bootcamp-korea/17-1st-SweetHome-backend pull request #17
Opened 2021-02-25 13:31 UTC by namujinju

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- ProductCartView Refactoring
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-25 13:56 UTC, jamessoun93 requested changes

2021-02-25 13:56 UTC, jamessoun93 commented on product/views.py
> +                order_product.save()
get() 메소드 쓰시면 꼭 exception 처리 해주셔야합니다. 어떤 exception 발생할 수 있는지 확인 후 처리해주세요.

2021-02-25 14:12 UTC, namujinju commented on product/views.py
> +                order_product.save()
수정 완료했습니다.

2021-02-25 16:49 UTC, jamessoun93 commented
conflict 해결해주세요.

2021-02-25 16:50 UTC, jamessoun93 requested changes

2021-02-25 16:50 UTC, jamessoun93 commented on order/views.py
> +            return JsonResponse({'message':'INVALID_ORDER'}, status=400)
get 메소드가 여러개의 객체를 반환할 시 raise 되는 exception 도 있습니다. 추가해주세요!

2021-02-25 21:45 UTC, namujinju commented on order/views.py
> +            return JsonResponse({'message':'INVALID_ORDER'}, status=400)
추가 완료했습니다!

2021-02-25 23:03 UTC, namujinju commented on order/views.py
> +            return JsonResponse({'message':'INVALID_ORDER'}, status=400)
주문이 제대로 동작하지 않아서 주문 로직도 변경했습니다.

2021-02-26 01:35 UTC, jamessoun93 commented
conflict 해결해주세요.

2021-02-26 01:41 UTC, jamessoun93 requested changes

2021-02-26 01:41 UTC, jamessoun93 commented on product/views.py
> +            data       = json.loads(request.body)
마찬가지입니다.

2021-02-26 01:41 UTC, jamessoun93 commented on order/views.py
> +            user = User.objects.get(id=1)
위에서 이미 유저객체 가지고 오는데 유저 하드코딩해서 받아오시는 방식으로 수정하신 이유가 있나요?

2021-02-26 01:41 UTC, jamessoun93 commented on order/views.py
> +            user = User.objects.get(id=1)
여기도 있네요.

2021-02-26 01:54 UTC, namujinju commented on order/views.py
> +            user = User.objects.get(id=1)
테스트를 위해 임시로 설정했습니다. 45분 전에 최종적으로 삭제해서 commit해서 push 했습니다. 혹시 적용이 안된 건가요?

2021-02-26 02:03 UTC, merged