[17기 박재현] order, posting 앱 models.py 수정
wecode-bootcamp-korea/17-1st-SweetHome-backend pull request #6
Opened 2021-02-22 12:03 UTC by namujinju

- 주문 상태를 나타내는 OrderStatus 모델 추가
- PostingComment 모델 posting 필드에 related_name 추가

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- order,posting 앱 models.py 수정
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 주문 상태를 나타내는 OrderStatus 모델 추가
- PostingComment 모델 posting 필드에 related_name 추가

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-22 12:07 UTC, soheon-lee commented on order/models.py
> +    user           = models.ForeignKey('user.User', on_delete=models.SET_NULL, null=True)
왜 user 컬럼이 orders 테이블에서 orderproducts 테이블로 이동했나요?

2021-02-22 12:51 UTC, namujinju commented on order/models.py
> +    user           = models.ForeignKey('user.User', on_delete=models.SET_NULL, null=True)
order_products 테이블은 user가 고른 상품들과 주문 상태에 대한 정보를 담고 있습니다. status 필드로 주문 상태(장바구니/결제완료)를 구분합니다. 
order 테이블은 user가 구매할 때 입력한 주문자/배송지에 대한 정보입니다.
user가 주어지고 status 값이 '결제완료'면 그 user에 해당하는 결제 내역(상품 + 주문자/배송지)을 확인할 수 있습니다.
즉, order_products 테이블이 user에 대한 장바구니와 결제내역에 대한 모든 정보를 가지고 있고, order 테이블은 단순히 주문자/배송지를 편리하게 모아놓은 테이블이기 때문에 user 필드를 뺐습니다.

2021-02-23 03:06 UTC, lordmyshepherd requested changes

2021-02-23 03:06 UTC, lordmyshepherd commented on order/models.py
> +    user           = models.ForeignKey('user.User', on_delete=models.SET_NULL, null=True)
**재현님!**

가장 많이 사용하는 주문 모델은 하나의 order로 관리합니다.
우선 `orderProduct` 테이블명을 `orderItem`으로 수정한 상태에서 설명드릴게요.

유저는 여러개의 `order`를 가질 수 있고, 현재 주문의 상태를 `order_status` (장바구니 / 결제완료) 테이블에서 관리합니다.
그렇기 때문에, order table이 user_id와 order_status_id를 가지고 있어야 합니다.

> 해당 오더의 결제가 완료된 이후에는 상태값을 결제완료로 바꾼 후에, 다음 주문을 진행할때는 order 레코드를 새로 생성하시면됩니다~

2021-02-23 05:00 UTC, namujinju commented on order/models.py
> +    user           = models.ForeignKey('user.User', on_delete=models.SET_NULL, null=True)
저희가 장바구니/주문내역의 역할을 하는 최종 주문 테이블을 잘못 선택한 것 같습니다. 기능 구현에 문제는 없었으나, orders 테이블을 최종 주문 테이블로 설정하고order_status(주문상태)와 user 정보로 장바구니를 불러오는 게 더 직관적인 로직일 것 같습니다. 팀원과 상의 후 수정하도록 하겠습니다.

2021-02-23 06:14 UTC, namujinju commented on order/models.py
> +    user           = models.ForeignKey('user.User', on_delete=models.SET_NULL, null=True)
현재 order_products 테이블이 user와 status, order_id로 장바구니와 주문에 대한 모든 정보를 나타낼 수 있으므로 이 테이블을 order로 바꾸고, 원래 order 테이블이었던 것은 order_detail_info로 바꾸도록 하겠습니다.

2021-02-23 07:23 UTC, namujinju commented on order/models.py
> +    user           = models.ForeignKey('user.User', on_delete=models.SET_NULL, null=True)
수정 완료했습니다.

2021-02-23 10:33 UTC, soheon-lee commented
LGTM

2021-02-23 10:33 UTC, merged